name: Update Fork

on:
  schedule:
    - cron: '0 0 * * *'  # Executa todo dia à meia-noite
  workflow_dispatch:  # Permite rodar manualmente

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Adicionar upstream
        run: |
          git remote add upstream https://github.com/nexus-comunicacao/client-platform.git
          git fetch upstream
          git checkout main
          git merge upstream/main --allow-unrelated-histories
          git push origin main
